### PR TITLE
Removed left search bar

### LINKED ISSUE #21: Show only one search bar at a time
_Originally posted by @lukpueh in https://github.com/DarikshaAnsari/in-toto-docs/issues/11#issuecomment-2295839965_

> > * Why are there two search bars, one in the right top corner and one in the left navigation column? (no need to fix this now, I'm just curious)
>
> If you don't want to fix this now, but close #8, please submit another issue so we can fix this separately.

### PR DESCRIPTION
**Pull request by DarikshaAnsari**
- Fixes #21

### CODE REVIEW

**Comment by DarikshaAnsari** [comment]
@chalin PTAL!!!

**Review by lukpueh — APPROVED** [review]
nice! @dindihub, can you adopt this for tuf? :)

**Comment by DarikshaAnsari** [comment]
@lukpueh Thank you for your review.

**Comment by Dindihub** [comment]
> nice! @Dindihub, can you adopt this for tuf? :)

 Noted. Thanks

**Pull request merged**
